source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'STComboBox_Example', :exclusive => true do
  pod "STComboBox", :path => "../"
end

target 'STComboBox_Tests', :exclusive => true do
  pod "STComboBox", :path => "../"

  pod 'FBSnapshotTestCase'
end
