source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'
inhibit_all_warnings!

target 'STComboBox_Example' do
  pod "STComboBox", :path => "../"
end

target 'STComboBox_Tests' do
  pod "STComboBox", :path => "../"

#pod 'FBSnapshotTestCase'
end
